package Taustaoperaatiot.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import Taustaoperaatiot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 11:43:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista88 
   * @throws SailoException when error
   */
  @Test
  public void testPoista88() throws SailoException {    // Joukkueet: 88
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue pittsburghpenguins21 = new Joukkue(); pittsburghpenguins21.dummyJoukkue(); 
    Joukkue pittsburghpenguins11 = new Joukkue(); pittsburghpenguins11.dummyJoukkue(); 
    Joukkue pittsburghpenguins22 = new Joukkue(); pittsburghpenguins22.dummyJoukkue(); 
    Joukkue pittsburghpenguins12 = new Joukkue(); pittsburghpenguins12.dummyJoukkue(); 
    Joukkue pittsburghpenguins23 = new Joukkue(); pittsburghpenguins23.dummyJoukkue(); 
    joukkueet.lisaa(pittsburghpenguins21); 
    joukkueet.lisaa(pittsburghpenguins11); 
    joukkueet.lisaa(pittsburghpenguins22); 
    joukkueet.lisaa(pittsburghpenguins12); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta118 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta118() throws SailoException {    // Joukkueet: 118
    Joukkueet jengit = new Joukkueet(); 
    Joukkue pittsburghpenguins21 = new Joukkue(); pittsburghpenguins21.dummyJoukkue(); 
    Joukkue pittsburghpenguins11 = new Joukkue(); pittsburghpenguins11.dummyJoukkue(); 
    Joukkue pittsburghpenguins22 = new Joukkue(); pittsburghpenguins22.dummyJoukkue(); 
    Joukkue pittsburghpenguins12 = new Joukkue(); pittsburghpenguins12.dummyJoukkue(); 
    Joukkue pittsburghpenguins23 = new Joukkue(); pittsburghpenguins23.dummyJoukkue(); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    jengit.lueTiedostosta(tiedNimi); 
    fail("Joukkueet: 132 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    jengit.lisaa(pittsburghpenguins21); 
    jengit.lisaa(pittsburghpenguins11); 
    jengit.lisaa(pittsburghpenguins22); 
    jengit.lisaa(pittsburghpenguins12); 
    jengit.lisaa(pittsburghpenguins23); 
    jengit.tallenna(); 
    jengit = new Joukkueet(); 
    jengit.lueTiedostosta(tiedNimi); 
    Iterator<Joukkue> i = jengit.iterator(); 
    assertEquals("From: Joukkueet line: 142", pittsburghpenguins21.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 143", pittsburghpenguins11.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 144", pittsburghpenguins22.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 145", pittsburghpenguins12.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 146", pittsburghpenguins23.toString(), i.next().toString()); 
    assertEquals("From: Joukkueet line: 147", false, i.hasNext()); 
    jengit.lisaa(pittsburghpenguins23); 
    jengit.tallenna(); 
    assertEquals("From: Joukkueet line: 150", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Joukkueet line: 152", true, fbak.delete()); 
  } // Generated by ComTest END
}