package Taustaoperaatiot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Taustaoperaatiot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 11:40:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testAnna335 */
  @Test
  public void testAnna335() {    // Joukkue: 335
    Joukkue jouk = new Joukkue(); 
    jouk.parse("1|PittsburghPenguins|Itäinen|Metropolitan|70"); 
    assertEquals("From: Joukkue line: 338", "1", jouk.anna(0)); 
    assertEquals("From: Joukkue line: 339", "PittsburghPenguins", jouk.anna(1)); 
    assertEquals("From: Joukkue line: 340", "Itäinen", jouk.anna(2)); 
    assertEquals("From: Joukkue line: 341", "Metropolitan", jouk.anna(3)); 
    assertEquals("From: Joukkue line: 342", "70", jouk.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta372 */
  @Test
  public void testAseta372() {    // Joukkue: 372
    Joukkue jouk = new Joukkue(); 
    assertEquals("From: Joukkue line: 374", null, jouk.aseta(1,"Pittsburgh Penguinskissa")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi451 */
  @Test
  public void testRekisteroi451() {    // Joukkue: 451
    Joukkue pittsburghpenguins1 = new Joukkue(); 
    pittsburghpenguins1.rekisteroi(); 
    Joukkue pittsburghpenguins2 = new Joukkue(); 
    pittsburghpenguins2.rekisteroi(); 
    int n1 = pittsburghpenguins1.getJoukkueID(); 
    int n2 = pittsburghpenguins2.getJoukkueID(); 
    assertEquals("From: Joukkue line: 458", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString472 */
  @Test
  public void testToString472() {    // Joukkue: 472
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("1|Pittsburgh|Itäinen|Metropolitan|70"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse498 */
  @Test
  public void testParse498() {    // Joukkue: 498
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("1|Pittsburgh|Itäinen|Metropolitan|70"); 
  } // Generated by ComTest END
}