package Taustaoperaatiot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Taustaoperaatiot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 11:39:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi138 */
  @Test
  public void testGetNimi138() {    // Pelaaja: 138
    Pelaaja sidney = new Pelaaja(); 
    sidney.dummyPelaaja(); 
    assertEquals("From: Pelaaja line: 141", "Teuvo Testi", sidney.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta391 */
  @Test
  public void testAseta391() {    // Pelaaja: 391
    Pelaaja pelaaja = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 393", null, pelaaja.aseta(2,"Sidney Crosby")); 
    assertEquals("From: Pelaaja line: 394", null, pelaaja.aseta(3,"Pittsburgh Penguins")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi526 */
  @Test
  public void testRekisteroi526() {    // Pelaaja: 526
    Pelaaja sidney1 = new Pelaaja(); 
    sidney1.rekisteroi(); 
    Pelaaja sidney2 = new Pelaaja(); 
    sidney2.rekisteroi(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString545 */
  @Test
  public void testToString545() {    // Pelaaja: 545
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1|Sidney Crosby|Pittsburgh Penguins"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse573 */
  @Test
  public void testParse573() {    // Pelaaja: 573
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1|Sidney Crosby|Pittsburgh Penguins"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals591 */
  @Test
  public void testEquals591() {    // Pelaaja: 591
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.parse("1|Sidney Crosby|PittsburghPenguins"); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("1|SidneyCrosby|PittsburghPenguins"); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("1|Sidney Crosby|PittsburghPenguins"); 
  } // Generated by ComTest END
}