package NHLtietokanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import NHLtietokanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.20 16:19:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi99 */
  @Test
  public void testRekisteroi99() {    // Joukkue: 99
    Joukkue pittsburghpenguins1 = new Joukkue(); 
    assertEquals("From: Joukkue line: 101", 0, pittsburghpenguins1.getTunnusNro()); 
    pittsburghpenguins1.rekisteroi(); 
    Joukkue pittsburghpenguins2 = new Joukkue(); 
    pittsburghpenguins2.rekisteroi(); 
    int n1 = pittsburghpenguins1.getJoukkueID(); 
    int n2 = pittsburghpenguins2.getJoukkueID(); 
    assertEquals("From: Joukkue line: 107", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString149 */
  @Test
  public void testToString149() {    // Joukkue: 149
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("   2   |  pittsburghpenguins  |   metropolitan  | itäinen | 22  "); 
    assertEquals("From: Joukkue line: 152", "2|pittsburghpenguins|metropolitan|itäinen|22", joukkue.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse167 */
  @Test
  public void testParse167() {    // Joukkue: 167
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("   2   |  10  |   pittsburghpenguins  | metropolitan | itäinen "); 
    assertEquals("From: Joukkue line: 170", 10, joukkue.getPelaajaID()); 
    assertEquals("From: Joukkue line: 171", "2|10|pittsburghpenguins|metropolitan|itäinen", joukkue.toString()); 
    joukkue.rekisteroi(); 
    int n = joukkue.getJoukkueID(); 
    joukkue.parse(""+(n+20)); 
    joukkue.rekisteroi(); 
    assertEquals("From: Joukkue line: 177", n+20+1, joukkue.getJoukkueID()); 
    assertEquals("From: Joukkue line: 178", "" + (n+20+1) + "2|10|pittsburghpenguins|metropolitan|itäinen", joukkue.toString()); 
  } // Generated by ComTest END
}