package NHLtietokanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import NHLtietokanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 13:06:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NHLtietokantaMainTest {
}